"""
Django settings for Companywebsite project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import hashlib
import importlib.util
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv(path):
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if value and len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ.setdefault(key, value)


load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return str(raw_value).strip().lower() in {"1", "true", "yes", "on"}


def env_csv(name, default=""):
    raw_value = os.getenv(name, default)
    return [item.strip() for item in str(raw_value).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-dev-key-change-this-before-production",
)


def build_mobile_jwt_signing_key(secret_key):
    raw_secret = str(secret_key or "")
    if len(raw_secret.encode("utf-8")) >= 32:
        return raw_secret
    # Keep deterministic fallback while enforcing minimum recommended entropy length for HS256.
    return hashlib.sha256(raw_secret.encode("utf-8")).hexdigest()


MOBILE_JWT_SIGNING_KEY = (
    os.getenv("MOBILE_JWT_SIGNING_KEY", "").strip() or build_mobile_jwt_signing_key(SECRET_KEY)
)

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_ENV = os.getenv("DJANGO_ENV", "local").strip().lower()
IS_PRODUCTION = DJANGO_ENV == "production"
IS_TEST = "test" in sys.argv

default_debug = not IS_PRODUCTION
DEBUG = env_bool("DJANGO_DEBUG", default_debug)

default_allowed_hosts = ["127.0.0.1", "localhost", "testserver"]
if DEBUG:
    default_allowed_hosts.append("0.0.0.0")
ALLOWED_HOSTS = env_csv("DJANGO_ALLOWED_HOSTS", ",".join(default_allowed_hosts))

default_csrf_origins = []
if DEBUG:
    default_csrf_origins = [
        "http://127.0.0.1",
        "http://localhost",
        "http://0.0.0.0",
        "https://127.0.0.1",
        "https://localhost",
        "https://0.0.0.0",
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "https://127.0.0.1:8000",
        "https://localhost:8000",
    ]
CSRF_TRUSTED_ORIGINS = env_csv("DJANGO_CSRF_TRUSTED_ORIGINS", ",".join(default_csrf_origins))

# Render dynamic hostname support (e.g. https://your-app.onrender.com)
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if RENDER_EXTERNAL_HOSTNAME:
    if RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'Myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'Myapp.middleware.ErrorLoggingMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Companywebsite.urls'

BASEDIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASEDIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Myapp.context_processors.admin_operational_summary',
                'Myapp.context_processors.user_notifications_summary',
            ],
        },
    },
]

WSGI_APPLICATION = 'Companywebsite.wsgi.application'
ASGI_APPLICATION = 'Companywebsite.asgi.application'

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL and len(REDIS_URL) >= 2 and REDIS_URL[0] == REDIS_URL[-1] and REDIS_URL[0] in {"'", '"'}:
    REDIS_URL = REDIS_URL[1:-1].strip()
HAS_CHANNELS_REDIS = importlib.util.find_spec("channels_redis") is not None
if REDIS_URL and HAS_CHANNELS_REDIS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

dj_database_url = None
try:
    import dj_database_url  # type: ignore
except ImportError:
    dj_database_url = None

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL and len(DATABASE_URL) >= 2 and DATABASE_URL[0] == DATABASE_URL[-1] and DATABASE_URL[0] in {"'", '"'}:
    DATABASE_URL = DATABASE_URL[1:-1].strip()
if DATABASE_URL.lower() in {"none", "null"}:
    DATABASE_URL = ""
if DATABASE_URL:
    if dj_database_url is None:
        raise RuntimeError("DATABASE_URL tanimli, fakat 'dj-database-url' paketi kurulu degil.")
    try:
        DATABASES = {
            "default": dj_database_url.parse(
                DATABASE_URL,
                conn_max_age=int(os.getenv("DATABASE_CONN_MAX_AGE", "600")),
                ssl_require=env_bool("DATABASE_SSL_REQUIRE", IS_PRODUCTION),
            )
        }
    except ValueError as exc:
        raise RuntimeError(
            "DATABASE_URL gecersiz. Render Postgres baglantisini kullanin veya degiskeni bos birakmak yerine tamamen kaldirin."
        ) from exc
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

# Cyprus local time for all datetime-local form parsing and UI rendering.
TIME_ZONE = 'Europe/Nicosia'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS=[

    os.path.join(BASEDIR, 'static'),
    
    ]

HAS_WHITENOISE = importlib.util.find_spec("whitenoise") is not None
USE_WHITENOISE = env_bool("USE_WHITENOISE", IS_PRODUCTION) and HAS_WHITENOISE
if USE_WHITENOISE and "whitenoise.middleware.WhiteNoiseMiddleware" not in MIDDLEWARE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'

# Cookie/Proxy settings to reduce CSRF/session issues on reverse proxies (Render).
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", (IS_PRODUCTION and not IS_TEST))
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", IS_PRODUCTION)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", IS_PRODUCTION)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", False)

# Marketplace runtime knobs
CALENDAR_FEATURE_ENABLED = env_bool("CALENDAR_FEATURE_ENABLED", True)
PROVIDER_AVAILABILITY_ENABLED = env_bool("PROVIDER_AVAILABILITY_ENABLED", False)
OFFER_EXPIRY_MINUTES = int(os.getenv("OFFER_EXPIRY_MINUTES", "180"))
OFFER_REMINDER_MINUTES = int(os.getenv("OFFER_REMINDER_MINUTES", "60"))
APPOINTMENT_PROVIDER_CONFIRM_MINUTES = int(os.getenv("APPOINTMENT_PROVIDER_CONFIRM_MINUTES", "720"))
APPOINTMENT_CUSTOMER_CONFIRM_MINUTES = int(os.getenv("APPOINTMENT_CUSTOMER_CONFIRM_MINUTES", "720"))
APPOINTMENT_SLOT_BUFFER_MINUTES = int(os.getenv("APPOINTMENT_SLOT_BUFFER_MINUTES", "45"))
APPOINTMENT_MIN_LEAD_MINUTES = int(os.getenv("APPOINTMENT_MIN_LEAD_MINUTES", "5"))
APPOINTMENT_LAST_MINUTE_CANCEL_HOURS = int(os.getenv("APPOINTMENT_LAST_MINUTE_CANCEL_HOURS", "6"))
APPOINTMENT_NO_SHOW_GRACE_MINUTES = int(os.getenv("APPOINTMENT_NO_SHOW_GRACE_MINUTES", "30"))
# Reliability
LOGIN_RATE_LIMIT_MAX_ATTEMPTS = int(os.getenv("LOGIN_RATE_LIMIT_MAX_ATTEMPTS", "15"))
LOGIN_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("LOGIN_RATE_LIMIT_WINDOW_SECONDS", "60"))
ACTION_RATE_LIMIT_MAX_ATTEMPTS = int(os.getenv("ACTION_RATE_LIMIT_MAX_ATTEMPTS", "40"))
ACTION_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("ACTION_RATE_LIMIT_WINDOW_SECONDS", "60"))
CREATE_REQUEST_RATE_LIMIT_MAX_ATTEMPTS = int(os.getenv("CREATE_REQUEST_RATE_LIMIT_MAX_ATTEMPTS", "8"))
CREATE_REQUEST_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("CREATE_REQUEST_RATE_LIMIT_WINDOW_SECONDS", "120"))
CREATE_REQUEST_DAILY_LIMIT = int(os.getenv("CREATE_REQUEST_DAILY_LIMIT", "20"))
CREATE_REQUEST_OPEN_LIMIT = int(os.getenv("CREATE_REQUEST_OPEN_LIMIT", "8"))
CREATE_REQUEST_IP_DAILY_LIMIT = int(os.getenv("CREATE_REQUEST_IP_DAILY_LIMIT", "80"))
CREATE_REQUEST_IP_BURST_LIMIT = int(os.getenv("CREATE_REQUEST_IP_BURST_LIMIT", "15"))
CREATE_REQUEST_IP_BURST_WINDOW_SECONDS = int(os.getenv("CREATE_REQUEST_IP_BURST_WINDOW_SECONDS", "600"))
CREATE_REQUEST_DUPLICATE_COOLDOWN_SECONDS = int(os.getenv("CREATE_REQUEST_DUPLICATE_COOLDOWN_SECONDS", "180"))
CREATE_REQUEST_MIN_INTERVAL_SECONDS = int(os.getenv("CREATE_REQUEST_MIN_INTERVAL_SECONDS", "30"))
POST_IDEMPOTENCY_TTL_SECONDS = int(os.getenv("POST_IDEMPOTENCY_TTL_SECONDS", "10"))
LIFECYCLE_HEARTBEAT_STALE_SECONDS = int(os.getenv("LIFECYCLE_HEARTBEAT_STALE_SECONDS", "180"))
LIFECYCLE_LOCK_TTL_SECONDS = int(os.getenv("LIFECYCLE_LOCK_TTL_SECONDS", "120"))
NAV_STREAM_INTERVAL_SECONDS = int(os.getenv("NAV_STREAM_INTERVAL_SECONDS", "8"))
NAV_STREAM_MAX_DURATION_SECONDS = int(os.getenv("NAV_STREAM_MAX_DURATION_SECONDS", "55"))
NAV_STREAM_REOPEN_MIN_SECONDS = int(os.getenv("NAV_STREAM_REOPEN_MIN_SECONDS", "2"))
REQUEST_MESSAGES_FALLBACK_POLL_INTERVAL_SECONDS = int(
    os.getenv("REQUEST_MESSAGES_FALLBACK_POLL_INTERVAL_SECONDS", "5")
)
NOTIFICATION_RETENTION_DAYS = int(os.getenv("NOTIFICATION_RETENTION_DAYS", "60"))
NOTIFICATION_UNREAD_CACHE_SECONDS = int(os.getenv("NOTIFICATION_UNREAD_CACHE_SECONDS", "6"))
CUSTOMER_SNAPSHOT_CACHE_SECONDS = int(os.getenv("CUSTOMER_SNAPSHOT_CACHE_SECONDS", "3"))
PROVIDER_SNAPSHOT_CACHE_SECONDS = int(os.getenv("PROVIDER_SNAPSHOT_CACHE_SECONDS", "3"))
MARKETPLACE_LIFECYCLE_WEB_REFRESH_INTERVAL_SECONDS = int(
    os.getenv("MARKETPLACE_LIFECYCLE_WEB_REFRESH_INTERVAL_SECONDS", "20")
)
HOUSEKEEPING_INTERVAL_SECONDS = int(os.getenv("HOUSEKEEPING_INTERVAL_SECONDS", "3600"))
IDEMPOTENCY_RETENTION_DAYS = int(os.getenv("IDEMPOTENCY_RETENTION_DAYS", "2"))
WORKFLOW_EVENT_RETENTION_DAYS = int(os.getenv("WORKFLOW_EVENT_RETENTION_DAYS", "90"))
ACTIVITY_LOG_RETENTION_DAYS = int(os.getenv("ACTIVITY_LOG_RETENTION_DAYS", "90"))
ERROR_LOG_RETENTION_DAYS = int(os.getenv("ERROR_LOG_RETENTION_DAYS", "30"))
MESSAGE_RETENTION_DAYS = int(os.getenv("MESSAGE_RETENTION_DAYS", "120"))
LIFECYCLE_HEALTH_TOKEN = os.getenv("LIFECYCLE_HEALTH_TOKEN", "").strip()
ERROR_LOGGING_ENABLED = env_bool("ERROR_LOGGING_ENABLED", True)
ERROR_LOG_TRACEBACK_MAX_CHARS = int(os.getenv("ERROR_LOG_TRACEBACK_MAX_CHARS", "12000"))
ERROR_LOG_MESSAGE_MAX_CHARS = int(os.getenv("ERROR_LOG_MESSAGE_MAX_CHARS", "500"))

# Mobile/API auth defaults
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("MOBILE_JWT_ACCESS_MINUTES", "30"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("MOBILE_JWT_REFRESH_DAYS", "14"))
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": MOBILE_JWT_SIGNING_KEY,
    "UPDATE_LAST_LOGIN": True,
}
