# Generated by Django 5.2.4 on 2026-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0031_mobiledevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
