# Generated by Django 5.2.4 on 2026-03-02 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0033_servicerequest_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_service_requests', to='Myapp.provider'),
        ),
    ]
