# Generated by Django 5.2.11 on 2026-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0034_servicerequest_preferred_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('customer-signup', 'Musteri Kaydi')], default='customer-signup', max_length=32)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['email', 'purpose', 'created_at'], name='Myapp_email_email_e0e1c8_idx'), models.Index(fields=['purpose', 'expires_at'], name='Myapp_email_purpose_5e7a1c_idx')],
            },
        ),
    ]
