# Generated by Codex on 2026-03-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0035_emailverificationcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowEventRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_event_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_entries",
                        to="Myapp.workflowevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="workfloweventread",
            constraint=models.UniqueConstraint(fields=("user", "workflow_event"), name="unique_workflow_event_read"),
        ),
        migrations.AddIndex(
            model_name="workfloweventread",
            index=models.Index(fields=["user", "read_at"], name="Myapp_workf_user_id_a9e0f2_idx"),
        ),
        migrations.AddIndex(
            model_name="workfloweventread",
            index=models.Index(fields=["workflow_event", "user"], name="Myapp_workf_workflo_d1b58f_idx"),
        ),
    ]
