# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0036_workfloweventread"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationcursor",
            name="allow_appointment_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationcursor",
            name="allow_message_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationcursor",
            name="allow_request_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
